"use client";
/* eslint-disable @next/next/no-img-element */
import { useCallback, useEffect, useRef, useState } from "react";
import { ExternalLink, Languages, Menu, Moon, Sun, X, Zap } from "lucide-react";
import type { MediaItem, StoredProject, StoredSection } from "@/lib/content-types";
import { categoryColor, categoryLabels, normalizeCategory } from "@/lib/project-presentation";
import { paletteStyle, type Settings } from "@/lib/site-settings";
import ContactForm from "./contact-form";
import ImmersiveTree from "./immersive-tree";
import WorldView from "./world-view";
import "./portfolio-effects.css";

type Lang="en"|"es"; type Presentation="immersive"|"standard"; type Realm="dark"|"light";
type Content={projects:StoredProject[];sections:StoredSection[];settings:Settings};
const tx=(en:string,es:string,lang:Lang)=>{const value=lang==="es"?(es||en):en;return /^0+\d+$/.test(value)?String(Number(value)):value};
const media=(item:{media:MediaItem[];mediaUrl:string;mediaType:string;mediaAlt?:string})=>item.media.length?item.media:item.mediaUrl?[{id:"legacy",url:item.mediaUrl,type:item.mediaType,alt:item.mediaAlt||""}]:[];
const sectionId=(s:StoredSection)=>s.kind==="hero"?"intro":s.kind==="profile"?"about":s.kind==="custom"?`section-${s.id}`:s.kind;
const sectionKinds=["work","profile","experience","contact"];

function StandardGallery({items,title}:{items:MediaItem[];title:string}){const [active,setActive]=useState(0),item=items[active];if(!item)return null;return <div className="standard-gallery"><div>{item.type.startsWith("video")?<video key={item.url} src={item.url} controls playsInline preload="metadata" poster={item.poster}/>:<img src={item.url} alt={item.alt||title}/>}</div>{items.length>1&&<nav aria-label="Gallery">{items.map((entry,index)=><button key={entry.id} aria-pressed={active===index} onClick={()=>setActive(index)}>{index+1}</button>)}</nav>}</div>}

function ProjectCard({project,lang,settings,onOpen}:{project:StoredProject;lang:Lang;settings:Settings;onOpen:()=>void}){const cover=media(project)[0],color=categoryColor(project,settings),category=normalizeCategory(project);return <article className="standard-project" style={{"--project-accent":color} as React.CSSProperties}>{cover&&<button className="standard-cover" onClick={onOpen} aria-label={`${lang==="es"?"Abrir":"Open"} ${tx(project.title,project.titleEs,lang)}`}>{cover.type.startsWith("video")?<video src={cover.url} muted playsInline preload="metadata" poster={cover.poster}/>:<img src={cover.url} alt={cover.alt||tx(project.title,project.titleEs,lang)}/>}</button>}<div className="standard-project-copy"><small>{categoryLabels[category][lang]}</small><h3>{tx(project.title,project.titleEs,lang)}</h3><p>{tx(project.description,project.descriptionEs,lang)}</p><div className="standard-tags">{project.stack.map(tag=><span key={tag}>{tag}</span>)}</div><button className="text-link" onClick={onOpen}>{lang==="es"?"Abrir caso":"Open case study"}</button></div></article>}

function StandardCase({project,lang,settings,onClose}:{project:StoredProject;lang:Lang;settings:Settings;onClose:()=>void}){const ref=useRef<HTMLElement>(null);useEffect(()=>{const overflow=document.body.style.overflow;document.body.style.overflow="hidden";ref.current?.querySelector<HTMLButtonElement>("button")?.focus();const key=(e:KeyboardEvent)=>e.key==="Escape"&&onClose();document.addEventListener("keydown",key);return()=>{document.body.style.overflow=overflow;document.removeEventListener("keydown",key);};},[onClose]);return <div className="standard-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><article ref={ref} className="standard-case" style={{"--project-accent":categoryColor(project,settings)} as React.CSSProperties} role="dialog" aria-modal="true"><button className="standard-close" onClick={onClose} aria-label="Close"><X/></button><small>{categoryLabels[normalizeCategory(project)][lang]}</small><h2>{tx(project.title,project.titleEs,lang)}</h2><strong>{tx(project.outcome,project.outcomeEs,lang)}</strong><p>{tx(project.description,project.descriptionEs,lang)}</p><StandardGallery items={media(project)} title={tx(project.title,project.titleEs,lang)}/><div className="standard-case-details">{(lang==="es"&&project.detailsEs.length?project.detailsEs:project.details).map((detail,index)=><p key={index}>{detail}</p>)}</div><div className="standard-tags">{project.stack.map(tag=><span key={tag}>{tag}</span>)}</div></article></div>}

function Intro({hero,lang}:{hero?:StoredSection;lang:Lang}){return <section className="cosmic-intro" id="intro"><div className="intro-stars" aria-hidden="true"/><div className="intro-copy"><span>Alejandro Urvieta</span><h1>Portfolio</h1><p>{hero?tx(hero.bodyEn,hero.bodyEs,lang):(lang==="es"?"Desarrollo de videojuegos, software y mundos interactivos.":"Game development, software and interactive worlds.")}</p></div><a className="intro-cue" href="#work"><i/><span>{lang==="es"?"Adéntrate":"Enter"}</span></a></section>}

export default function Portfolio({initialData}:{initialData:Content}){
 const {projects,sections,settings}=initialData;const [lang,setLang]=useState<Lang>("en"),[realm,setRealm]=useState<Realm>("dark"),[presentation,setPresentation]=useState<Presentation>(settings.defaultPresentation),[effectsPref,setEffectsPref]=useState<"auto"|"on"|"off">("auto"),[lowPower,setLowPower]=useState(true),[reduced,setReduced]=useState(false),[ready,setReady]=useState(false),[navVisible,setNavVisible]=useState(false),[menuOpen,setMenuOpen]=useState(false),[selected,setSelected]=useState<StoredProject|null>(null);
 const hero=sections.find(s=>s.kind==="hero"),visibleSections=sections.filter(s=>s.kind!=="hero"&&s.kind!=="work"&&s.published);const effects=ready&&!reduced&&effectsPref!=="off"&&(effectsPref==="on"||!lowPower)&&settings.motionLevel>0;
 useEffect(()=>{queueMicrotask(()=>{try{const storedLang=localStorage.getItem("au-lang"),storedRealm=localStorage.getItem("au-theme"),storedPresentation=localStorage.getItem("au-presentation"),storedEffects=localStorage.getItem("au-effects");if(storedLang==="es")setLang("es");if(storedRealm==="light")setRealm("light");if(storedPresentation==="standard"||storedPresentation==="immersive")setPresentation(storedPresentation);if(storedEffects==="on"||storedEffects==="off")setEffectsPref(storedEffects);}catch{}const nav=navigator as Navigator&{deviceMemory?:number;connection?:{saveData?:boolean}};setLowPower((nav.hardwareConcurrency||8)<6||(nav.deviceMemory||8)<4||!!nav.connection?.saveData);const mq=matchMedia("(prefers-reduced-motion: reduce)");setReduced(mq.matches);setReady(true);});const mq=matchMedia("(prefers-reduced-motion: reduce)"),change=()=>setReduced(mq.matches);mq.addEventListener("change",change);return()=>mq.removeEventListener("change",change);},[]);
 useEffect(()=>{document.documentElement.dataset.theme=realm;document.documentElement.lang=lang;for(const [key,value] of Object.entries(paletteStyle(settings.palette[realm])))document.documentElement.style.setProperty(key,String(value));if(ready)try{localStorage.setItem("au-lang",lang);localStorage.setItem("au-theme",realm);localStorage.setItem("au-presentation",presentation);localStorage.setItem("au-effects",effectsPref);}catch{}},[lang,realm,presentation,effectsPref,ready,settings.palette]);
 useEffect(()=>{let previous=scrollY;const move=(event:MouseEvent)=>{if(presentation==="immersive"&&event.clientY<70)setNavVisible(true);};const scroll=()=>{const y=scrollY,show=y<80||y<previous;setNavVisible(presentation==="standard"||show);if(y>previous)setMenuOpen(false);previous=y;};window.addEventListener("mousemove",move,{passive:true});window.addEventListener("scroll",scroll,{passive:true});scroll();return()=>{window.removeEventListener("mousemove",move);window.removeEventListener("scroll",scroll);};},[presentation]);
 useEffect(()=>{const sync=()=>{const hashId=Number(window.location.hash.match(/^#world-(\d+)$/)?.[1]),id=Number(window.history.state?.portfolioWorld??hashId);setSelected(projects.find(project=>project.id===id)??null)};sync();window.addEventListener("popstate",sync);return()=>window.removeEventListener("popstate",sync);},[projects]);
 const openProject=useCallback((project:StoredProject)=>{if(presentation==="immersive")history.pushState({portfolioWorld:project.id},"",`#world-${project.id}`);setSelected(project);},[presentation]);
 const closeProject=useCallback(()=>{if(presentation==="immersive"&&history.state?.portfolioWorld)history.back();else setSelected(null);},[presentation]);
 const navSections=sections.filter(s=>sectionKinds.includes(s.kind));
 return <main className="portfolio-v2" data-presentation={presentation} data-realm={realm} data-effects={effects?"on":"off"}>
  <a className="skip-link" href="#work">{lang==="es"?"Ir a proyectos":"Skip to work"}</a><Intro hero={hero} lang={lang}/>
  <header className={`site-nav ${navVisible||menuOpen?"is-visible":""}`} onFocusCapture={()=>setNavVisible(true)}><a className="site-brand" href="#intro"><span>AU</span><strong>Alejandro Urvieta</strong></a><nav className={menuOpen?"is-open":""} aria-label={lang==="es"?"Navegación principal":"Main navigation"}>{navSections.map(s=><a key={s.id} href={`#${sectionId(s)}`} onClick={()=>setMenuOpen(false)}>{s.kind==="work"?(lang==="es"?"Proyectos":"Work"):s.kind==="profile"?(lang==="es"?"Perfil":"Profile"):s.kind==="experience"?(lang==="es"?"Experiencia":"Experience"):(lang==="es"?"Contacto":"Contact")}</a>)}</nav><div className="site-controls"><button className="presentation-toggle" onClick={()=>setPresentation(presentation==="immersive"?"standard":"immersive")}><span>{presentation==="immersive"?(lang==="es"?"Vista estándar":"Standard view"):(lang==="es"?"Vista inmersiva":"Immersive view")}</span></button><label className="effects-toggle"><Zap/><select aria-label={lang==="es"?"Efectos":"Effects"} value={effectsPref} onChange={e=>setEffectsPref(e.target.value as typeof effectsPref)}><option value="auto">Auto</option><option value="on">On</option><option value="off">Off</option></select></label><button onClick={()=>setLang(lang==="en"?"es":"en")} aria-label={lang==="en"?"Cambiar a español":"Switch to English"}><Languages/><span>{lang==="en"?"ES":"EN"}</span></button><button className="realm-toggle" onClick={()=>setRealm(realm==="dark"?"light":"dark")} aria-label={lang==="es"?"Cambiar reino":"Change realm"}>{realm==="dark"?<Sun/>:<Moon/>}</button><button className="mobile-menu" onClick={()=>setMenuOpen(!menuOpen)} aria-label={lang==="es"?"Abrir menú":"Open menu"}>{menuOpen?<X/>:<Menu/>}</button></div></header>
  {presentation==="immersive"?<ImmersiveTree projects={projects} settings={settings} lang={lang} realm={realm} effects={effects} onOpen={openProject}/>:<section id="work" className="standard-work"><header><h2>{lang==="es"?"Proyectos seleccionados":"Selected work"}</h2><p>{lang==="es"?"Programación, herramientas, arte técnico y experiencias interactivas.":"Programming, tools, technical art and interactive experiences."}</p></header><div className="standard-grid">{projects.map(project=><ProjectCard key={project.id} project={project} lang={lang} settings={settings} onOpen={()=>openProject(project)}/>)}</div></section>}
  <div className="content-after-world">{visibleSections.map(section=>{const title=tx(section.titleEn,section.titleEs,lang),body=tx(section.bodyEn,section.bodyEs,lang);if(section.kind==="highlights")return <section key={section.id} className="quiet-highlights">{section.items.map(item=><div key={item.titleEn}><strong>{tx(item.titleEn,item.titleEs,lang)}</strong><span>{tx(item.bodyEn,item.bodyEs,lang)}</span></div>)}</section>;if(section.kind==="profile")return <section key={section.id} id="about" className="editorial-section profile-section"><header><h2>{title}</h2><p>{body}</p></header><div className="principle-list">{section.items.filter(i=>i.label!=="skill").map(item=><article key={item.titleEn}><h3>{tx(item.titleEn,item.titleEs,lang)}</h3><p>{tx(item.bodyEn,item.bodyEs,lang)}</p></article>)}</div><div className="skill-list">{section.items.filter(i=>i.label==="skill").map(item=><span key={item.titleEn}>{tx(item.titleEn,item.titleEs,lang)}</span>)}</div></section>;if(section.kind==="experience")return <section key={section.id} id="experience" className="editorial-section experience-section"><header><h2>{lang==="es"?"Experiencia":"Experience"}</h2></header><div>{section.items.map((item,index)=>{const [role,...detail]=tx(item.bodyEn,item.bodyEs,lang).split("\n");return <article key={index}><time>{lang==="es"?item.label.replace("NOW","AHORA"):item.label}</time><div><strong>{tx(item.titleEn,item.titleEs,lang)}</strong><h3>{role}</h3></div><p>{detail.join("\n")}</p></article>})}</div></section>;if(section.kind==="contact")return <section key={section.id} id="contact" className="editorial-section contact-section"><header><h2>{title}</h2><p>{body}</p></header><ContactForm lang={lang} magical={presentation==="immersive"&&effects}/><nav>{section.items.filter(i=>!i.href.startsWith("mailto:")).map(item=><a key={item.href} href={item.href} target="_blank" rel="noreferrer">{tx(item.titleEn,item.titleEs,lang)}<ExternalLink/></a>)}</nav></section>;return <section key={section.id} id={sectionId(section)} className="editorial-section"><header><h2>{title}</h2><p>{body}</p></header></section>})}</div>
  <footer><span>© {new Date().getFullYear()} Alejandro Urvieta González</span><span>Querétaro, México</span></footer>
  {selected&&(presentation==="immersive"?<WorldView project={selected} lang={lang} color={categoryColor(selected,settings)} onClose={closeProject}/>:<StandardCase project={selected} lang={lang} settings={settings} onClose={closeProject}/>)}
 </main>;
}
