export type Lang = "en" | "es";
export type Track = "programming" | "art" | "hybrid";
export type Localized = { en: string; es: string };
export type Project = {
  title: Localized; code: string; track: Track; kind: string; description: Localized;
  outcome: Localized; details: Localized[]; stack: string[]; href?: string; repo?: string;
  accent: "color 1" | "color 2" | "color 3" | "color 4" | "color 5"; featured?: boolean;
  mediaUrl?: string; mediaType?: string; mediaAlt?: string;
};
const l = (en: string, es: string): Localized => ({ en, es });

export const projects: Project[] = [
  {title:l("MeasureSystem Real-Time","MeasureSystem Real-Time"),code:"MS—01",track:"programming",kind:"Unity Editor Tool",description:l("A production-ready Unity utility for inspecting dimensions and measuring distances directly in the Scene view.","Una herramienta lista para producción que inspecciona dimensiones y mide distancias directamente en la vista Scene de Unity."),outcome:l("Published on the Unity Asset Store by Attribute Overload","Publicada en Unity Asset Store por Attribute Overload"),details:[l("Designed the editor workflow around fast selection and immediate visual feedback for level and asset teams.","Diseñé el flujo de editor alrededor de selección rápida y retroalimentación visual inmediata para equipos de niveles y assets."),l("Implemented the C# architecture, editor UI, unit conversion, real-time measurements and automated tests.","Implementé la arquitectura en C#, interfaz de editor, conversión de unidades, mediciones en tiempo real y pruebas automatizadas."),l("Supported packaging and review through the complete Unity Asset Store approval process.","Apoyé el empaquetado y la revisión durante todo el proceso de aprobación de Unity Asset Store.")],stack:["Unity","C#","Editor Tools","Unit Tests"],href:"https://assetstore.unity.com/packages/tools/utilities/measuresystem-real-time-302689",accent:"color 1",featured:true},
  {title:l("The Exit 8 — Systems Study","The Exit 8 — Estudio de sistemas"),code:"UE—02",track:"hybrid",kind:"UE5 Gameplay",description:l("A technical recreation of anomaly logic, loop progression and environmental interactions in Unreal Engine 5.","Recreación técnica de lógica de anomalías, progresión en bucle e interacciones ambientales en Unreal Engine 5."),outcome:l("Playable environment built around reusable Blueprint systems","Entorno jugable construido con sistemas reutilizables en Blueprint"),details:[l("Developed doors, cameras, teleportation, level transitions and win-state logic as reusable Blueprints.","Desarrollé puertas, cámaras, teletransporte, transiciones y condición de victoria como Blueprints reutilizables."),l("Combined level pacing, AI behavior, lighting and environmental audio to communicate anomalies clearly.","Combiné ritmo de nivel, IA, iluminación y audio ambiental para comunicar anomalías con claridad.")],stack:["Unreal Engine 5","Blueprints","Gameplay","Level Design"],href:"https://github.com/Simiobanana/Replicated-The-Exit-8",repo:"https://github.com/Simiobanana/Replicated-The-Exit-8",accent:"color 2"},
  {title:l("BananasEngine","BananasEngine"),code:"DX—03",track:"programming",kind:"Graphics Engine",description:l("A lightweight C++ graphics engine with OBJ loading, transforms, lighting and live scene controls through ImGui.","Motor gráfico ligero en C++ con carga OBJ, transformaciones, iluminación y controles de escena mediante ImGui."),outcome:l("A four-month deep dive into real-time rendering fundamentals","Cuatro meses de trabajo sobre fundamentos de render en tiempo real"),details:[l("Worked directly with the rendering pipeline, mesh data, camera transforms, materials and scene state.","Trabajé directamente con el pipeline de render, datos de malla, cámara, materiales y estado de escena."),l("Built practical debugging controls that made visual iteration faster and rendering behavior easier to inspect.","Construí controles de depuración para acelerar la iteración visual e inspeccionar el comportamiento del render.")],stack:["C++","DirectX","ImGui","Rendering"],href:"https://github.com/Simiobanana/BananasEngine",repo:"https://github.com/Simiobanana/BananasEngine",accent:"color 3"},
  {title:l("Ká Hai — Interactive 3D","Ká Hai — Web 3D interactiva"),code:"WEB—04",track:"hybrid",kind:"Client Web",description:l("A responsive production website with two interactive GLB viewers, camera controls and live PBR material customization.","Sitio responsivo en producción con dos visores GLB, controles de cámara y personalización de materiales PBR."),outcome:l("Final client website delivered and operating online","Sitio final entregado al cliente y funcionando en línea"),details:[l("Connected browser-based 3D interaction with a responsive interface and an asynchronous contact workflow.","Integré interacción 3D en navegador con una interfaz responsiva y un flujo de contacto asíncrono."),l("Optimized the experience for desktop and mobile while preserving product detail and direct manipulation.","Optimicé la experiencia para escritorio y móvil conservando detalle de producto y manipulación directa.")],stack:["JavaScript","model-viewer","PBR","Responsive Web"],href:"https://jdie2026.github.io/Ha-Kai/",accent:"color 4"},
  {title:l("Automaton Hunters","Cazadores de Autómatas"),code:"VR—05",track:"hybrid",kind:"Unity VR",description:l("A team VR game I led while contributing directly to gameplay, interaction and interface systems.","Juego VR en equipo que lideré mientras contribuía directamente al gameplay, interacción e interfaz."),outcome:l("Project leadership plus hands-on gameplay programming","Liderazgo de proyecto y programación directa de gameplay"),details:[l("Programmed scoring, timer, menus, enemy–bullet collisions and enemy movement along splines.","Programé puntuación, temporizador, menús, colisiones enemigo–bala y movimiento de enemigos mediante splines."),l("Built the complete settings flow, assisted weapon functionality and coordinated the team toward delivery.","Construí el flujo completo de ajustes, apoyé la funcionalidad del arma y coordiné al equipo hasta la entrega.")],stack:["Unity","C#","VR","UI / UX","Spline AI"],accent:"color 5"},
  {title:l("Shields, Trails, Beams & Orbs","Escudos, estelas, rayos y orbes"),code:"VFX—06",track:"art",kind:"Real-time VFX",description:l("A focused Unreal Engine 5 collection exploring readable silhouettes, energy motion and layered gameplay feedback.","Colección en Unreal Engine 5 que explora siluetas legibles, movimiento de energía y feedback de gameplay por capas."),outcome:l("Four reusable Niagara studies with distinct visual languages","Cuatro estudios reutilizables de Niagara con lenguajes visuales distintos"),details:[l("Built shield, trail, beam and orb effects as modular visual-feedback blocks for gameplay.","Construí efectos de escudo, estela, rayo y orbe como bloques modulares de feedback para gameplay."),l("Balanced materials, timing, color and particle density so each effect remains readable during action.","Equilibré materiales, timing, color y densidad de partículas para mantener legibilidad durante la acción.")],stack:["UE5","Niagara","Materials","VFX"],accent:"color 3"},
  {title:l("Environment & Material Studies","Estudios de entornos y materiales"),code:"ART—07",track:"art",kind:"3D Art",description:l("Real-time scenes studying composition, lighting, terrain, materials and asset integration.","Escenas en tiempo real para estudiar composición, iluminación, terreno, materiales e integración de assets."),outcome:l("World-building practice grounded in real-time constraints","Práctica de world building basada en restricciones de tiempo real"),details:[l("Explored how atmosphere, composition and material response guide attention through a playable scene.","Exploré cómo atmósfera, composición y respuesta de materiales guían la atención en una escena jugable."),l("Connected artistic decisions with performance-aware workflows in Unity and Unreal Engine.","Conecté decisiones artísticas con flujos conscientes del rendimiento en Unity y Unreal Engine.")],stack:["Unreal Engine","Unity","Blender","Substance"],href:"https://github.com/Simiobanana/Enviroments",repo:"https://github.com/Simiobanana/Enviroments",accent:"color 1"},
  {title:l("Procedural Material Programming","Programación de materiales"),code:"MAT—08",track:"hybrid",kind:"Technical Art",description:l("Material and environment exercises joining shader logic, procedural controls and visual composition.","Ejercicios de materiales y entornos que unen lógica de shaders, controles procedurales y composición visual."),outcome:l("Technical-art studies for responsive real-time worlds","Estudios de arte técnico para mundos interactivos en tiempo real"),details:[l("Created a nature-focused scene inspired by God of War (2018) while practicing programmable materials.","Creé una escena natural inspirada en God of War (2018) mientras practicaba materiales programables."),l("Used exposed parameters and reusable logic to make visual iteration faster and more predictable.","Usé parámetros expuestos y lógica reutilizable para hacer la iteración visual más rápida y predecible.")],stack:["Shaders","Materials","Unreal Engine","Technical Art"],href:"https://github.com/Simiobanana/Programacion-De-Materiales",repo:"https://github.com/Simiobanana/Programacion-De-Materiales",accent:"color 2"}
];

export const jobs = [
  ["2026—NOW","JaRo Labs",l("Co-founder","Cofundador"),l("3D modeling and printing, machine maintenance, orders and operational dashboards.","Modelado e impresión 3D, mantenimiento, pedidos y dashboards operativos.")],
  ["2025","Freelance",l("UE5 / Blender instructor","Instructor UE5 / Blender"),l("Taught modeling, texturing, asset integration and Blueprint fundamentals.","Enseñé modelado, texturizado, integración de assets y fundamentos de Blueprints.")],
  ["2024","Attribute Overload",l("Unity Developer Intern","Unity Developer Intern"),l("Built editor tooling, tests and UI; supported backend integration and AI navigation research.","Construí tooling, pruebas y UI; apoyé integración backend e investigación de navegación con IA.")],
  ["2024","Icaro Technologies",l("Unity Backend Programmer","Programador Backend Unity"),l("Developed VR mechanics for an educational milling-machine simulation.","Desarrollé mecánicas VR para una simulación educativa de fresadora.")]
] as const;
