"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowDown, ArrowUpRight, Braces, Code2, ExternalLink, Gamepad2, GitFork, Languages, Mail, MapPin, Moon, Palette, Sparkles, Sun, X } from "lucide-react";
import { jobs, Lang, Project, projects, Track } from "./portfolio-data";

type Settings={accentCyan:string;accentViolet:string;motionLevel:number;heroTitleEn:string;heroTitleEs:string;heroTextEn:string;heroTextEs:string;availabilityEn:string;availabilityEs:string};
type CustomSection={id:number;eyebrowEn:string;eyebrowEs:string;titleEn:string;titleEs:string;bodyEn:string;bodyEs:string;linkLabelEn?:string|null;linkLabelEs?:string|null;href?:string|null;mediaUrl?:string|null;mediaType?:string|null;published:boolean};
const defaults:Settings={accentCyan:"#31e9ff",accentViolet:"#9d6cff",motionLevel:2,heroTitleEn:"I engineer playable ideas.",heroTitleEs:"Convierto ideas en experiencias jugables.",heroTextEn:"Game and software developer focused on Unity, C# and Unreal Engine 5.",heroTextEs:"Desarrollador de videojuegos y software enfocado en Unity, C# y Unreal Engine 5.",availabilityEn:"Available for new opportunities",availabilityEs:"Disponible para nuevas oportunidades"};
const copy={
 en:{nav:["Work","Profile","Experience","Contact"],kicker:"GAME SYSTEMS · CREATOR TOOLS · REAL-TIME VFX",explore:"Explore selected work",talk:"Start a conversation",facts:["Querétaro, Mexico","English B2","Available immediately"],proof:[["01","Published tool"],["4+","Years building"],["08","Selected projects"],["03","Creative disciplines"]],workTitle:"Code, art and the space between.",workText:"Production work and focused studies across gameplay, tools, graphics, VFX and interactive web.",filters:{all:"All work",programming:"Programming",art:"Art & VFX",hybrid:"Hybrid"},view:"Open case study",live:"Visit project",source:"Source",about:"A developer who thinks in systems and pictures.",aboutText:"I move comfortably between code and visual craft. That range helps me prototype clearly, communicate across disciplines and turn complex mechanics into experiences people can read and enjoy.",principles:[["Design for feedback","Every interaction should explain what happened."],["Build for iteration","Reusable systems make the next idea faster."],["Protect the frame","Visual impact only works when information stays clear."]],experience:"EXPERIENCE",contact:"Have a difficult idea? Let’s make it playable.",contactText:"Open to game development, tools, software, technical art and interactive web opportunities.",email:"Email me",scroll:"Scroll to work",built:"Designed and built in Querétaro"},
 es:{nav:["Proyectos","Perfil","Experiencia","Contacto"],kicker:"SISTEMAS DE JUEGO · CREATOR TOOLS · VFX EN TIEMPO REAL",explore:"Explorar proyectos",talk:"Iniciar una conversación",facts:["Querétaro, México","Inglés B2","Disponibilidad inmediata"],proof:[["01","Herramienta publicada"],["4+","Años creando"],["08","Proyectos seleccionados"],["03","Disciplinas creativas"]],workTitle:"Código, arte y el espacio entre ambos.",workText:"Trabajo profesional y estudios enfocados en gameplay, tools, gráficos, VFX y web interactiva.",filters:{all:"Todos",programming:"Programación",art:"Arte y VFX",hybrid:"Híbridos"},view:"Abrir caso",live:"Visitar proyecto",source:"Código",about:"Un desarrollador que piensa en sistemas e imágenes.",aboutText:"Me muevo con comodidad entre el código y el trabajo visual. Ese rango me ayuda a prototipar con claridad, comunicarme entre disciplinas y convertir mecánicas complejas en experiencias legibles y disfrutables.",principles:[["Diseñar para el feedback","Cada interacción debe explicar qué ocurrió."],["Construir para iterar","Los sistemas reutilizables aceleran la siguiente idea."],["Cuidar el encuadre","El impacto visual funciona cuando la información permanece clara."]],experience:"EXPERIENCIA",contact:"¿Tienes una idea difícil? Hagamos que se pueda jugar.",contactText:"Disponible para oportunidades en videojuegos, tools, software, arte técnico y web interactiva.",email:"Escríbeme",scroll:"Ir a proyectos",built:"Diseñado y construido en Querétaro"}
};

function Media({url,type,alt}:{url?:string;type?:string;alt?:string}){if(!url)return <><span className="visual-grid"/><span className="visual-ring"/><span className="visual-beam"/></>;return type?.startsWith("video")?<video src={url} muted loop autoPlay playsInline aria-label={alt}/>:<img src={url} alt={alt||""}/>;}

export default function Portfolio(){
 const [theme,setTheme]=useState<"dark"|"light">("dark"),[lang,setLang]=useState<Lang>("en"),[filter,setFilter]=useState<"all"|Track>("all"),[added,setAdded]=useState<Project[]>([]),[sections,setSections]=useState<CustomSection[]>([]),[settings,setSettings]=useState(defaults),[selected,setSelected]=useState<Project|null>(null),[navVisible,setNavVisible]=useState(true);
 const lastY=useRef(0),t=copy[lang];
 useEffect(()=>{const stored=localStorage.getItem("au-theme");const next=stored==="light"?"light":"dark";setTheme(next);document.documentElement.dataset.theme=next;const savedLang=localStorage.getItem("au-lang");if(savedLang==="es")setLang("es")},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("au-theme",theme)},[theme]);
 useEffect(()=>{document.documentElement.lang=lang;localStorage.setItem("au-lang",lang)},[lang]);
 useEffect(()=>{Promise.all([fetch("/api/projects").then(r=>r.json()),fetch("/api/sections").then(r=>r.json()),fetch("/api/settings").then(r=>r.json())]).then(([p,s,c])=>{setAdded((p.projects??[]).filter((x:{published:boolean})=>x.published).map((x:any,i:number)=>({title:{en:x.title,es:x.titleEs||x.title},description:{en:x.description,es:x.descriptionEs||x.description},outcome:{en:x.outcome,es:x.outcomeEs||x.outcome},details:(x.details?.length?x.details:[x.description]).map((d:string,j:number)=>({en:d,es:x.detailsEs?.[j]||d})),code:`NEW—${String(i+1).padStart(2,"0")}`,track:(x.category==="Art & VFX"?"art":x.category==="Hybrid"?"hybrid":"programming") as Track,kind:x.category,stack:x.stack||[],href:x.href,repo:x.repo,featured:x.featured,mediaUrl:x.mediaUrl,mediaType:x.mediaType,mediaAlt:x.mediaAlt,accent:["violet","amber","lime","rose"][i%4]})));setSections((s.sections??[]).filter((x:CustomSection)=>x.published));setSettings(c.settings??defaults)}).catch(()=>{})},[]);
 useEffect(()=>{const onScroll=()=>{const y=window.scrollY;document.documentElement.style.setProperty("--scroll-shift",`${Math.min(y*.07,96)}px`);setNavVisible(y<80||y<lastY.current-2);lastY.current=y};window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);
 useEffect(()=>{document.body.style.overflow=selected?"hidden":"";if(!selected)return;const close=(e:KeyboardEvent)=>e.key==="Escape"&&setSelected(null);window.addEventListener("keydown",close);return()=>{document.body.style.overflow="";window.removeEventListener("keydown",close)}},[selected]);
 const visible=useMemo(()=>[...projects,...added].filter(p=>filter==="all"||p.track===filter),[filter,added]);
 const style={"--custom-cyan":settings.accentCyan,"--custom-violet":settings.accentViolet} as React.CSSProperties;
 const heroTitle=lang==="en"?settings.heroTitleEn:settings.heroTitleEs,heroText=lang==="en"?settings.heroTextEn:settings.heroTextEs,availability=lang==="en"?settings.availabilityEn:settings.availabilityEs;
 return <main style={style} data-motion={settings.motionLevel}>
  <a className="skip-link" href="#work">Skip to work</a><div className="aurora" aria-hidden="true"><i/><i/><i/><span className="laser l1"/><span className="laser l2"/><span className="laser l3"/></div><div className="noise" aria-hidden="true"/>
  <header className={`nav-wrap ${navVisible?"":"nav-hidden"}`}><a className="brand" href="#top" aria-label="Alejandro Urvieta, home"><span className="brand-mark">AU</span><span><strong>Alejandro Urvieta</strong><small>Game & Software Developer</small></span></a><nav aria-label={lang==="en"?"Main navigation":"Navegación principal"}>{["work","about","experience","contact"].map((id,i)=><a href={`#${id}`} key={id}>{t.nav[i]}</a>)}</nav><div className="nav-controls"><button className="control" onClick={()=>setLang(lang==="en"?"es":"en")} aria-label={lang==="en"?"Cambiar a español":"Switch to English"}><Languages size={16}/><span>{lang==="en"?"ES":"EN"}</span></button><button className="control icon-only" onClick={()=>setTheme(theme==="dark"?"light":"dark")} aria-label={theme==="dark"?"Use light theme":"Usar tema oscuro"}>{theme==="dark"?<Sun size={17}/>:<Moon size={17}/>}</button></div></header>
  <section className="hero" id="top"><div className="hero-copy"><div className="status"><i/> {availability}<span>· Querétaro / Remote</span></div><p className="kicker">{t.kicker}</p><h1>{heroTitle}</h1><p className="hero-lede">{heroText}</p><div className="hero-actions"><a className="button primary" href="#work">{t.explore}<ArrowDown size={17}/></a><a className="button ghost" href="mailto:alejandroug2608@gmail.com">{t.talk}<Mail size={17}/></a></div><div className="hero-facts">{t.facts.map((x,i)=><span key={x}>{i===0&&<MapPin size={14}/>} {x}</span>)}</div></div>
   <div className="hero-console glass" aria-label="Creative development disciplines"><div className="console-top"><span>CREATIVE_SYSTEMS.EXE</span><span className="live-dot">LIVE</span></div><div className="console-stage"><div className="core"><Gamepad2 size={30}/><strong>PLAY</strong><small>code × craft</small></div><span className="node n1"><Code2/>GAMEPLAY</span><span className="node n2"><Braces/>TOOLS</span><span className="node n3"><Palette/>VFX</span><span className="node n4"><Sparkles/>WORLDS</span><div className="scanline"/></div><div className="console-foot"><span>UNITY · UE5 · C++ · WEB</span><strong>READY_01</strong></div></div>
  </section>
  <a className="scroll-cue" href="#work"><span>{t.scroll}</span><ArrowDown size={15}/></a>
  <section className="proof-strip" aria-label="Highlights">{t.proof.map(([v,label])=><div key={label}><strong>{v}</strong><span>{label}</span></div>)}</section>
  <section className="work section-shell" id="work"><div className="section-index">01 / SELECTED WORK</div><div className="section-head"><h2>{t.workTitle}</h2><p>{t.workText}</p></div><div className="filters" role="group" aria-label="Project filters">{(["all","programming","art","hybrid"] as const).map(k=><button key={k} aria-pressed={filter===k} className={filter===k?"active":""} onClick={()=>setFilter(k)}>{t.filters[k]}</button>)}</div><div className="project-grid">{visible.map((p,i)=><article className={`project-card glass accent-${p.accent} ${p.featured?"featured":""}`} key={p.code}><div className="project-media"><Media url={p.mediaUrl} type={p.mediaType} alt={p.mediaAlt||p.title[lang]}/><span className="project-number">{String(i+1).padStart(2,"0")}</span><span className="project-kind">{p.kind}</span></div><div className="project-body"><p className="outcome">{p.outcome[lang]}</p><h3>{p.title[lang]}</h3><p>{p.description[lang]}</p><div className="tags">{p.stack.map(x=><span key={x}>{x}</span>)}</div><button className="case-link" onClick={()=>setSelected(p)}>{t.view}<ArrowUpRight size={16}/></button></div></article>)}</div></section>
  {sections.map((s,i)=><section className="custom-feature section-shell glass" key={s.id}><div className="custom-copy"><p className="section-index">{String(i+2).padStart(2,"0")} / {lang==="en"?s.eyebrowEn:s.eyebrowEs}</p><h2>{lang==="en"?s.titleEn:s.titleEs}</h2><p>{lang==="en"?s.bodyEn:s.bodyEs}</p>{s.href&&<a className="button ghost" href={s.href} target="_blank" rel="noreferrer">{lang==="en"?s.linkLabelEn:s.linkLabelEs}<ExternalLink size={16}/></a>}</div>{s.mediaUrl&&<div className="custom-media"><Media url={s.mediaUrl} type={s.mediaType} alt={lang==="en"?s.titleEn:s.titleEs}/></div>}</section>)}
  <section className="about section-shell" id="about"><div className="section-index">02 / {lang==="en"?"PROFILE":"PERFIL"}</div><div className="about-intro"><h2>{t.about}</h2><p>{t.aboutText}</p></div><div className="principles">{t.principles.map(([h,p],i)=><article key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p></article>)}</div><div className="skill-rail"><span>UNITY</span><span>UNREAL ENGINE 5</span><span>C#</span><span>C++</span><span>NIAGARA</span><span>BLENDER</span><span>SQL</span><span>AWS</span><span>WEB 3D</span></div></section>
  <section className="experience section-shell" id="experience"><div className="section-index">03 / {t.experience}</div><div className="timeline">{jobs.map(([date,company,role,detail],i)=><article key={company}><span className="timeline-no">{String(i+1).padStart(2,"0")}</span><span className="timeline-date">{lang==="es"?date.replace("NOW","AHORA"):date}</span><div><strong>{company}</strong><h3>{role[lang]}</h3></div><p>{detail[lang]}</p></article>)}</div></section>
  <section className="contact section-shell glass" id="contact"><p className="kicker">NEXT QUEST / 04</p><h2>{t.contact}</h2><p>{t.contactText}</p><div className="hero-actions"><a className="button primary" href="mailto:alejandroug2608@gmail.com">{t.email}<Mail size={17}/></a><a className="button ghost" href="https://github.com/Simiobanana" target="_blank" rel="noreferrer">GitHub<GitFork size={17}/></a><a className="button ghost" href="/CV_Alejandro_Tools_EN.pdf" target="_blank">CV · EN<ExternalLink size={15}/></a><a className="button ghost" href="/CV_Alejandro_Software_ES.pdf" target="_blank">CV · ES<ExternalLink size={15}/></a></div></section>
  <footer><span>© 2026 Alejandro Urvieta González</span><span>{t.built}</span></footer>
  {selected&&<div className="case-overlay" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><article className={`case-modal glass accent-${selected.accent}`} role="dialog" aria-modal="true" aria-labelledby="case-title"><button className="case-close" onClick={()=>setSelected(null)} aria-label={lang==="en"?"Close case study":"Cerrar caso"}><X size={20}/></button><p className="section-index">{selected.code} / {selected.kind}</p><h2 id="case-title">{selected.title[lang]}</h2><p className="case-outcome">{selected.outcome[lang]}</p><p className="case-summary">{selected.description[lang]}</p><div className="case-details">{selected.details.map((d,i)=><div key={i}><span>{String(i+1).padStart(2,"0")}</span><p>{d[lang]}</p></div>)}</div><div className="tags">{selected.stack.map(x=><span key={x}>{x}</span>)}</div>{(selected.href||selected.repo)&&<div className="case-actions">{selected.href&&<a className="button primary" href={selected.href} target="_blank" rel="noreferrer">{t.live}<ArrowUpRight size={17}/></a>}{selected.repo&&selected.repo!==selected.href&&<a className="button ghost" href={selected.repo} target="_blank" rel="noreferrer">{t.source}<GitFork size={17}/></a>}</div>}</article></div>}
 </main>
}
