"use client";
/* eslint-disable @next/next/no-img-element */

import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Code2, GitFork, Languages, Mail, MapPin, Moon, Sun, X } from "lucide-react";

type Lang="en"|"es"; type Track="programming"|"art"|"hybrid"; type L={en:string;es:string};
type Project={title:L;code:string;track:Track;kind:string;description:L;outcome:L;details:L[];stack:string[];href?:string;repo?:string;accent:string;featured?:boolean;mediaUrl?:string;mediaType?:string};
const l=(en:string,es:string):L=>({en,es});

const projects:Project[]=[
 {title:l("MeasureSystem Real-Time","MeasureSystem Real-Time"),code:"MS—01",track:"programming",kind:"Unity Tool",description:l("A Unity editor utility for inspecting dimensions and measuring distances between selected points in real time.","Herramienta de editor para inspeccionar dimensiones y medir distancias entre puntos seleccionados en tiempo real."),outcome:l("Published by Attribute Overload on Unity Asset Store","Publicada por Attribute Overload en Unity Asset Store"),details:[l("Built during a professional internship with a clear architecture and a practical workflow for level and asset teams.","Creada durante prácticas profesionales con una arquitectura clara y un flujo práctico para equipos de niveles y assets."),l("Implemented editor UI, real-time measurements and unit tests, then supported the release through Asset Store approval.","Implementé UI de editor, mediciones en tiempo real y pruebas unitarias, y apoyé la publicación hasta su aprobación.")],stack:["Unity","C#","Editor Tools","Unit Tests"],href:"https://assetstore.unity.com/packages/tools/utilities/measuresystem-real-time-302689",accent:"cyan",featured:true},
 {title:l("The Exit 8 — Systems Study","The Exit 8 — Estudio de sistemas"),code:"UE—02",track:"hybrid",kind:"UE5 Gameplay",description:l("A technical recreation of anomaly logic, win conditions and level transitions supported by environmental audio.","Recreación técnica de anomalías, condición de victoria y transiciones de nivel con audio ambiental."),outcome:l("Playable environmental system built in Unreal Engine 5","Sistema ambiental jugable construido en Unreal Engine 5"),details:[l("Developed gameplay Blueprints for doors, teleportation, cameras and environmental interactions.","Desarrollé Blueprints para puertas, teletransporte, cámaras e interacciones ambientales."),l("Combined systems design, level pacing, AI behavior and audio to study how a looping space communicates anomalies.","Combiné diseño de sistemas, ritmo de nivel, IA y audio para estudiar cómo un espacio en bucle comunica anomalías.")],stack:["UE5","Blueprints","Gameplay","Environment"],href:"https://github.com/Simiobanana/Replicated-The-Exit-8",repo:"https://github.com/Simiobanana/Replicated-The-Exit-8",accent:"violet"},
 {title:l("BananasEngine","BananasEngine"),code:"DX—03",track:"programming",kind:"Graphics Engine",description:l("A lightweight graphics engine with OBJ loading, transforms, color and lighting controls through ImGui.","Motor gráfico ligero con carga de OBJ, transformaciones y controles de color e iluminación mediante ImGui."),outcome:l("Four-month academic graphics project","Proyecto académico de gráficos desarrollado durante cuatro meses"),details:[l("Worked directly with the rendering pipeline to understand mesh loading, transformations, materials and scene controls.","Trabajé con el pipeline de render para comprender carga de mallas, transformaciones, materiales y controles de escena.")],stack:["C++","DirectX","ImGui","Graphics"],href:"https://github.com/Simiobanana/BananasEngine",repo:"https://github.com/Simiobanana/BananasEngine",accent:"amber"},
 {title:l("Ká Hai — Interactive 3D","Ká Hai — Web 3D interactiva"),code:"WEB—04",track:"hybrid",kind:"Client Web",description:l("A published client website with two interactive GLB viewers, camera controls, PBR material adjustment and asynchronous contact.","Sitio publicado para cliente con dos visores GLB, controles de cámara, ajuste de materiales PBR y contacto asíncrono."),outcome:l("Live client website delivered and operating","Sitio final del cliente publicado y operativo"),details:[l("Connected browser-based 3D interaction with a responsive static site and Formspree contact integration.","Integré interacción 3D en navegador con un sitio responsivo y contacto mediante Formspree."),l("The link opens the final production website delivered to the client.","El enlace abre el sitio final de producción entregado al cliente.")],stack:["JavaScript","model-viewer","PBR","Formspree"],href:"https://jdie2026.github.io/Ha-Kai/",accent:"lime"},
 {title:l("Automaton Hunters","Cazadores de Autómatas"),code:"VR—05",track:"hybrid",kind:"Unity VR",description:l("A team VR game where I led the project and contributed directly to gameplay and interaction systems.","Juego VR en equipo que lideré mientras contribuía directamente al gameplay y los sistemas de interacción."),outcome:l("Project leadership and gameplay programming","Liderazgo de proyecto y programación de gameplay"),details:[l("Programmed scoring, timer, UI navigation and interactions, enemy–bullet collisions and enemy movement along splines.","Programé puntuación, temporizador, navegación e interacciones de UI, colisiones y movimiento de enemigos mediante splines."),l("Built the complete settings menu and assisted with weapon functionality while coordinating delivery.","Construí el menú de ajustes y apoyé la funcionalidad del arma mientras coordinaba la entrega.")],stack:["Unity VR","C#","UI / UX","Spline AI"],accent:"rose"},
 {title:l("Shields, Trails, Beams & Orbs","Escudos, estelas, rayos y orbes"),code:"VFX—06",track:"art",kind:"UE5 VFX",description:l("A real-time VFX showcase exploring readable silhouettes, energy motion and layered visual feedback in Unreal Engine 5.","Muestra de VFX en tiempo real que explora siluetas legibles, energía y retroalimentación visual por capas en Unreal Engine 5."),outcome:l("Four-effect Unreal Engine 5 showcase","Muestra de cuatro efectos creada en Unreal Engine 5"),details:[l("The collection includes shield, trail, beam and orb studies designed as reusable gameplay-feedback blocks.","La colección incluye escudos, estelas, rayos y orbes diseñados como bloques reutilizables para gameplay."),l("The work combines Niagara, materials and timing to balance visual impact with readability.","El trabajo combina Niagara, materiales y timing para equilibrar impacto visual y legibilidad.")],stack:["UE5","Niagara","Materials","Real-time VFX"],accent:"violet"},
 {title:l("Environment & Material Studies","Estudios de entornos y materiales"),code:"ART—07",track:"art",kind:"3D Art",description:l("Environment and material studies inspired by natural landscapes, built with real-time engines and 3D art tools.","Estudios de entornos y materiales inspirados en paisajes naturales, creados con motores en tiempo real y herramientas 3D."),outcome:l("World building, composition and material practice","Práctica de world building, composición y materiales"),details:[l("Explored composition, lighting, terrain, asset integration and material response in academic and personal scenes.","Exploré composición, iluminación, terreno, integración de assets y respuesta de materiales en escenas académicas y personales."),l("The studies connect artistic decisions with the technical constraints of real-time engines.","Los estudios conectan decisiones artísticas con las restricciones técnicas de motores en tiempo real.")],stack:["Unreal Engine","Unity","Blender","Substance"],href:"https://github.com/Simiobanana/Enviroments",repo:"https://github.com/Simiobanana/Enviroments",accent:"amber"},
 {title:l("Procedural Material Programming","Programación de materiales"),code:"MAT—08",track:"hybrid",kind:"Technical Art",description:l("A collection of real-time material and environment exercises joining shader logic with visual composition.","Colección de ejercicios de materiales y entornos en tiempo real que une lógica de shaders con composición visual."),outcome:l("Technical art studies for real-time worlds","Estudios de arte técnico para mundos en tiempo real"),details:[l("Created a nature-focused scene inspired by God of War (2018) while practicing programmable materials and engine workflows.","Creé una escena de naturaleza inspirada en God of War (2018) mientras practicaba materiales programables y flujos de motor.")],stack:["Shaders","Materials","Unreal Engine","Technical Art"],href:"https://github.com/Simiobanana/Programacion-De-Materiales",repo:"https://github.com/Simiobanana/Programacion-De-Materiales",accent:"lime"}
];

const copy={
 en:{nav:["Work","Profile","Contact"],status:"Available for new opportunities · Querétaro / remote",kicker:"CREATOR TOOLS · GAMEPLAY · VFX · INTERACTIVE SOFTWARE",title:"I build systems that make ideas",em:"playable.",lede:"Game and software developer focused on Unity, C# and Unreal Engine 5. My work spans published tools, VR worlds, real-time VFX, C++ graphics and interactive 3D websites.",explore:"Explore projects",talk:"Let’s talk",facts:["Querétaro, Mexico","English B2","Available immediately"],proof:[["2024","Game Development graduate"],["4+","Years creating with Unity & UE"],["01","Published Asset Store tool"],["∞","Technical curiosity"]],workTitle:"Code, art and the space between.",workText:"Browse programming work, visual development and hybrid projects where both disciplines shape the result.",filters:{all:"All",programming:"Programming",art:"Art & VFX",hybrid:"Hybrid"},view:"View case study",live:"Open project",source:"View source",about:"From a hard problem to a clear experience.",aboutText:"I combine systems thinking, visual judgment and curiosity. I turn complex mechanics into tools and experiences a team can understand, test and improve.",caps:[["Game systems","Gameplay, UI, VR, AI and editor tools."],["Software","C#, C++, Python, databases and AWS services."],["Technical art","Niagara, Shader Graph, materials and real-time VFX."]],experience:"EXPERIENCE LOG",contact:"Let’s build something worth exploring.",contactText:"I’m looking for opportunities in game development, tools, software, technical art and interactive web.",email:"Send email",built:"Designed & built in Querétaro"},
 es:{nav:["Proyectos","Perfil","Contacto"],status:"Disponible para nuevas oportunidades · Querétaro / remoto",kicker:"CREATOR TOOLS · GAMEPLAY · VFX · SOFTWARE INTERACTIVO",title:"Construyo sistemas que hacen que las ideas",em:"se puedan jugar.",lede:"Desarrollador de videojuegos y software enfocado en Unity, C# y Unreal Engine 5. Mi trabajo abarca herramientas publicadas, mundos VR, VFX en tiempo real, gráficos en C++ y sitios web 3D interactivos.",explore:"Explorar proyectos",talk:"Hablemos",facts:["Querétaro, México","Inglés B2","Disponible de inmediato"],proof:[["2024","Graduado en Desarrollo de Videojuegos"],["4+","Años creando con Unity y UE"],["01","Herramienta publicada"],["∞","Curiosidad técnica"]],workTitle:"Código, arte y el espacio entre ambos.",workText:"Explora proyectos de programación, desarrollo visual y casos híbridos donde ambas disciplinas definen el resultado.",filters:{all:"Todos",programming:"Programación",art:"Arte y VFX",hybrid:"Híbridos"},view:"Ver caso",live:"Abrir proyecto",source:"Ver código",about:"Del problema a una experiencia clara.",aboutText:"Combino pensamiento de sistemas, criterio visual y curiosidad. Convierto mecánicas complejas en herramientas y experiencias que un equipo puede entender, probar y mejorar.",caps:[["Sistemas de juego","Gameplay, UI, VR, IA y herramientas de editor."],["Software","C#, C++, Python, bases de datos y servicios AWS."],["Arte técnico","Niagara, Shader Graph, materiales y VFX en tiempo real."]],experience:"EXPERIENCIA",contact:"Construyamos algo que valga la pena explorar.",contactText:"Busco oportunidades en desarrollo de videojuegos, tools, software, arte técnico y web interactiva.",email:"Enviar correo",built:"Diseñado y construido en Querétaro"}
};
const jobs=[
 ["2026—NOW","JaRo Labs",l("Co-founder","Cofundador"),l("3D modeling and printing, machine maintenance, orders and dashboards.","Modelado e impresión 3D, mantenimiento, pedidos y dashboards.")],
 ["2025","Freelance",l("UE5 / Blender instructor","Instructor UE5 / Blender"),l("Modeling, texturing, asset integration and Blueprint fundamentals.","Modelado, texturizado, integración de assets y fundamentos de Blueprints.")],
 ["2024","Attribute Overload",l("Unity Developer Intern","Unity Developer Intern"),l("Tooling, unit tests, UI, backend integration and AI navigation research.","Tooling, pruebas unitarias, UI, integración backend e investigación de navegación IA.")],
 ["2024","Icaro Technologies",l("Unity Backend Programmer","Programador Backend Unity"),l("VR mechanics for an educational milling-machine simulation.","Mecánicas VR para una simulación educativa de fresadora.")]
] as const;

export default function Portfolio(){
 const [theme,setTheme]=useState<"dark"|"light">("dark"),[lang,setLang]=useState<Lang>("en"),[filter,setFilter]=useState<"all"|Track>("all"),[added,setAdded]=useState<Project[]>([]),[selected,setSelected]=useState<Project|null>(null),[navVisible,setNavVisible]=useState(true); const t=copy[lang];
 useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);
 useEffect(()=>{document.documentElement.lang=lang},[lang]);
 useEffect(()=>{let last=window.scrollY;let timer:ReturnType<typeof setTimeout>;const onScroll=()=>{const y=window.scrollY;document.documentElement.style.setProperty("--scroll-shift",`${Math.min(y*.08,90)}px`);setNavVisible(y<72||y<last-3?true:y>last+5?false:navVisible);last=y;clearTimeout(timer);timer=setTimeout(()=>setNavVisible(true),650)};window.addEventListener("scroll",onScroll,{passive:true});return()=>{window.removeEventListener("scroll",onScroll);clearTimeout(timer)}},[navVisible]);
 useEffect(()=>{fetch("/api/projects").then(r=>r.json()).then(d=>setAdded((d.projects??[]).filter((p:{published:boolean})=>p.published).map((p:{title:string;description:string;outcome:string;category:string;stack:string[];href?:string;repo?:string;featured?:boolean;mediaUrl?:string;mediaType?:string},i:number)=>({title:l(p.title,p.title),description:l(p.description,p.description),outcome:l(p.outcome,p.outcome),details:[l(p.description,p.description)],code:`NEW—${String(i+1).padStart(2,"0")}`,track:(p.category==="Art & VFX"?"art":p.category==="Hybrid"?"hybrid":"programming") as Track,kind:p.category,stack:p.stack,href:p.href,repo:p.repo,featured:p.featured,mediaUrl:p.mediaUrl,mediaType:p.mediaType,accent:["violet","amber","lime","rose"][i%4]})))).catch(()=>{})},[]);
 useEffect(()=>{document.body.style.overflow=selected?"hidden":"";return()=>{document.body.style.overflow=""}},[selected]);
 const visible=useMemo(()=>[...projects,...added].filter(p=>filter==="all"||p.track===filter),[filter,added]);
 const filterKeys:(Track|"all")[]=["all","programming","art","hybrid"];
 return <main><div className="ambient-lights" aria-hidden="true"><i/><i/><i/><span/></div><div className="noise" aria-hidden="true"/>
  <header className={`nav-wrap ${navVisible?"":"nav-hidden"}`}><a className="brand" href="#top"><span className="brand-mark">AU</span><span><strong>Alejandro Urvieta</strong><small>Game & Software Developer</small></span></a><nav aria-label={lang==="en"?"Main navigation":"Navegación principal"}><a href="#work">{t.nav[0]}</a><a href="#about">{t.nav[1]}</a><a href="#contact">{t.nav[2]}</a></nav><div className="nav-controls"><button className="language-switch" onClick={()=>setLang(lang==="en"?"es":"en")}><Languages size={15}/>{lang==="en"?"ES":"EN"}</button><button className="theme-switch" onClick={()=>setTheme(theme==="dark"?"light":"dark")} aria-label="Theme">{theme==="dark"?<Sun size={17}/>:<Moon size={17}/>}</button></div></header>
  <section className="hero" id="top"><div className="hero-copy"><div className="status"><span/> {t.status}</div><p className="kicker">{t.kicker}</p><h1>{t.title} <em>{t.em}</em></h1><p className="hero-lede">{t.lede}</p><div className="hero-actions"><a className="button primary" href="#work">{t.explore}<ArrowUpRight size={18}/></a><a className="button ghost" href="mailto:alejandroug2608@gmail.com">{t.talk}<Mail size={17}/></a><a className="button ghost" href="/CV_Alejandro_Tools_EN.pdf" target="_blank">CV · EN</a><a className="button ghost" href="/CV_Alejandro_Software_ES.pdf" target="_blank">CV · ES</a></div><div className="hero-facts"><span><MapPin size={14}/>{t.facts[0]}</span><span>{t.facts[1]}</span><span>{t.facts[2]}</span></div></div><div className="signal-stage"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="core"><Code2 size={28}/><strong>BUILD</strong><small>systems / art / worlds</small></div><span className="satellite sat-1">UNITY</span><span className="satellite sat-2">UE5</span><span className="satellite sat-3">C++</span><span className="satellite sat-4">VFX</span><div className="telemetry"><span>01</span><p>{lang==="en"?"Published product":"Producto publicado"}</p><strong>Unity Asset Store</strong></div></div></section>
  <section className="proof-strip">{t.proof.map(([v,label])=><div key={label}><strong>{v}</strong><span>{label}</span></div>)}</section>
  <section className="work" id="work"><div className="section-head"><div><p className="kicker">SELECTED WORK / 2022—2026</p><h2>{t.workTitle}</h2></div><p>{t.workText}</p></div><div className="filters">{filterKeys.map(k=><button key={k} className={filter===k?"active":""} onClick={()=>setFilter(k)}>{t.filters[k]}</button>)}</div><div className="project-grid">{visible.map((p,i)=><article className={`project-card glass accent-${p.accent} ${p.featured?"featured":""}`} key={p.code}><div className="project-top"><span>{p.code}</span><span>{p.kind}</span></div><div className={`project-visual ${p.mediaUrl?"has-media":""}`}>{p.mediaUrl&&(p.mediaType?.startsWith("video")?<video src={p.mediaUrl} muted loop autoPlay playsInline/>:<img src={p.mediaUrl} alt=""/>)}<span className="visual-grid"/><span className="visual-disc"/><span className="visual-line"/><b>{String(i+1).padStart(2,"0")}</b></div><div className="project-body"><p className="outcome">{p.outcome[lang]}</p><h3>{p.title[lang]}</h3><p>{p.description[lang]}</p><div className="tags">{p.stack.map(x=><span key={x}>{x}</span>)}</div><div className="project-links"><button className="case-link" onClick={()=>setSelected(p)}>{t.view}<ArrowUpRight size={16}/></button></div></div></article>)}</div></section>
  <section className="about" id="about"><div className="about-number">A/01</div><div><p className="kicker">{lang==="en"?"HOW I WORK":"CÓMO TRABAJO"}</p><h2>{t.about}</h2><p className="about-lede">{t.aboutText}</p></div><div className="capabilities">{t.caps.map(([h,p],i)=><div key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p></div>)}</div></section>
  <section className="experience"><p className="kicker">{t.experience}</p>{jobs.map(([date,company,role,detail])=><div className="experience-row" key={company}><span>{lang==="es"?date.replace("NOW","AHORA"):date}</span><strong>{company}</strong><h3>{role[lang]}</h3><p>{detail[lang]}</p></div>)}</section>
  <section className="contact glass" id="contact"><p className="kicker">NEXT QUEST</p><h2>{t.contact}</h2><p>{t.contactText}</p><div className="hero-actions"><a className="button primary" href="mailto:alejandroug2608@gmail.com">{t.email}<Mail size={17}/></a><a className="button ghost" href="https://github.com/Simiobanana" target="_blank" rel="noreferrer">GitHub<GitFork size={17}/></a></div></section>
  <footer><span>© 2026 Alejandro Urvieta González</span><span>{t.built}</span></footer>
  {selected&&<div className="case-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><article className={`case-modal glass accent-${selected.accent}`} role="dialog" aria-modal="true" aria-labelledby="case-title"><button className="case-close" onClick={()=>setSelected(null)}><X size={20}/></button><p className="kicker">{selected.code} · {selected.kind}</p><h2 id="case-title">{selected.title[lang]}</h2><p className="case-outcome">{selected.outcome[lang]}</p><p className="case-summary">{selected.description[lang]}</p><div className="case-details">{selected.details.map((d,i)=><p key={i}><span>0{i+1}</span>{d[lang]}</p>)}</div><div className="tags">{selected.stack.map(x=><span key={x}>{x}</span>)}</div>{(selected.href||selected.repo)&&<div className="case-actions">{selected.href&&<a className="button primary" href={selected.href} target="_blank" rel="noreferrer">{t.live}<ArrowUpRight size={17}/></a>}{selected.repo&&selected.repo!==selected.href&&<a className="button ghost" href={selected.repo} target="_blank" rel="noreferrer">{t.source}<GitFork size={17}/></a>}</div>}</article></div>}
 </main>
}
