"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ExternalLink, GitFork, X } from "lucide-react";
import type { MediaItem, StoredProject } from "@/lib/content-types";
import { categoryLabels, normalizeCategory } from "@/lib/project-presentation";

type Lang="en"|"es";
function PortalGallery({items,title}:{items:MediaItem[];title:string}){const [active,setActive]=useState(0),item=items[active];if(!item)return null;return <div className="portal-gallery"><div className={`portal-frame portal-shape-${active%3}`}>{item.type.startsWith("video")?<video key={item.url} src={item.url} controls playsInline preload="metadata" poster={item.poster} aria-label={item.alt||title}/>:<img src={item.url} alt={item.alt||title}/>}</div>{items.length>1&&<div className="portal-thumbs" role="group" aria-label="Gallery">{items.map((entry,index)=><button key={entry.id} onClick={()=>setActive(index)} aria-pressed={index===active}><span>{index+1}</span>{entry.type.startsWith("video")?"Video":"Image"}</button>)}</div>}</div>}

export default function WorldView({project,lang,color,onClose}:{project:StoredProject;lang:Lang;color:string;onClose:()=>void}){
 const ref=useRef<HTMLElement>(null),category=normalizeCategory(project),media=project.media.length?project.media:project.mediaUrl?[{id:"legacy",url:project.mediaUrl,type:project.mediaType,alt:project.mediaAlt}]:[];
 useEffect(()=>{const overflow=document.body.style.overflow,before=document.activeElement as HTMLElement|null;document.body.style.overflow="hidden";ref.current?.querySelector<HTMLButtonElement>("button")?.focus();const key=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();};document.addEventListener("keydown",key);return()=>{document.body.style.overflow=overflow;document.removeEventListener("keydown",key);before?.focus();};},[onClose]);
 return <div className="world-overlay" style={{"--world-color":color} as React.CSSProperties}><div className="portal-transition" aria-hidden="true"/><article ref={ref} className="world-view" role="dialog" aria-modal="true" aria-labelledby="world-title"><header><button className="world-back" onClick={onClose}><ArrowLeft/>{lang==="es"?"Volver al árbol":"Back to the tree"}</button><button className="world-x" onClick={onClose} aria-label={lang==="es"?"Cerrar proyecto":"Close project"}><X/></button></header><div className="world-hero"><p>{categoryLabels[category][lang]}</p><h2 id="world-title">{lang==="es"?project.titleEs:project.title}</h2><strong>{lang==="es"?project.outcomeEs:project.outcome}</strong></div><PortalGallery items={media} title={lang==="es"?project.titleEs:project.title}/><div className="world-content"><section className="rune-panel world-description"><h3>{lang==="es"?"El mundo":"The world"}</h3><p>{lang==="es"?project.descriptionEs:project.description}</p></section><section className="rune-panel world-outcome"><h3>{lang==="es"?"Resultado":"Outcome"}</h3><p>{lang==="es"?project.outcomeEs:project.outcome}</p></section><section className="rune-panel world-details"><h3>{lang==="es"?"Cómo fue construido":"How it was built"}</h3>{(lang==="es"&&project.detailsEs.length?project.detailsEs:project.details).map((detail,index)=><p key={index}>{detail}</p>)}</section><section className="world-runes"><h3>{lang==="es"?"Tecnologías":"Technologies"}</h3><div>{project.stack.map(value=><span key={value}>{value}</span>)}</div></section>{(project.href||project.repo)&&<div className="world-actions">{project.href&&project.href!=="#"&&<a href={project.href} target="_blank" rel="noreferrer">{lang==="es"?"Visitar proyecto":"Visit project"}<ExternalLink/></a>}{project.repo&&project.repo!==project.href&&<a href={project.repo} target="_blank" rel="noreferrer">{lang==="es"?"Ver código":"View source"}<GitFork/></a>}</div>}</div></article></div>;
}
